Add account creation functionality
hyperledger/sawtooth-marketplace pull request #17
Opened 2017-12-05 20:04 UTC by dplumb94

Signed-off-by: Darian Plumb <dplumb@bitwise.io>

2017-12-05 22:25 UTC, delventhalz requested changes

2017-12-06 11:18 UTC, peterschwarz approved these changes

2017-12-06 11:18 UTC, peterschwarz commented on rest_api/api/accounts.py
> +    context = create_context('secp256k1')
This context should be created once for the application.

2017-12-06 18:02 UTC, delventhalz approved these changes

2017-12-06 18:02 UTC, merged