Implement account fetch routes
hyperledger/sawtooth-marketplace pull request #27
Opened 2017-12-06 21:08 UTC by dplumb94

Signed-off-by: Darian Plumb <dplumb@bitwise.io>

2017-12-06 22:01 UTC, boydjohnson approved these changes

2017-12-07 17:24 UTC, delventhalz requested changes

2017-12-07 17:24 UTC, delventhalz commented on rest_api/db/accounts_query.py
> +                'email': auth_query.fetch_email(account['public_key'])
We should consider email (and any other auth info) to be semi-private, and not send it back with `GET /accounts`. I will submit a PR to update the spec to clarify this.

2017-12-07 17:24 UTC, delventhalz commented on rest_api/db/accounts_query.py
> +                    'email': auth_query.fetch_email(key)
Auth info should only get sent back with `GET /accounts/{key}` if the user is authorized and fetching info for themselves.

2017-12-07 19:32 UTC, delventhalz approved these changes

2017-12-07 19:33 UTC, merged