Create offer
hyperledger/sawtooth-marketplace pull request #50
Opened 2017-12-12 19:42 UTC by dplumb94

2017-12-12 19:59 UTC, boydjohnson commented on transaction_creation/marketplace_transaction/transaction_creation.py
> +               addresser.make_account_address(
I don't think the Account is an output of the txn. Only the Offer will be created, and no holdings will be modified until the Offer is Accepted.

2017-12-12 19:59 UTC, boydjohnson requested changes
Outputs should be slightly modified in create_offer.

2017-12-12 21:56 UTC, boydjohnson approved these changes

2017-12-12 23:46 UTC, delventhalz requested changes

2017-12-12 23:46 UTC, delventhalz commented on rest_api/api/offers.py
> +        offer['targetQuantity'] = 0
I'm not sure this correct given our recent Slack discussion. A source quantity of 0 is never valid, and a target quantity of 0 is only valid if target is also unspecified. I think it is probably best to leave these fields unset. In most cases, the validator will spit back an invalid transaction anyway. In the event that both target and targetQuantity are unset, leaving them unset in the response object seems sensible to me.

2017-12-12 23:46 UTC, delventhalz commented on rest_api/api-spec.yaml
> +      - type
As per our recent Slack discussion, `target` and `targetQuantity` should be removed from the `required` field of `NewOfferBody`

2017-12-12 23:46 UTC, delventhalz commented on rest_api/api/offers.py
> +    required_fields = ['source', 'sourceQuantity', 'target', 'targetQuantity']
`target` and `targetQuantity` are not required.

2017-12-12 23:54 UTC, delventhalz commented
Also, this test should be fixed:
```
fail: POST (200) /offers duration: 271ms
fail: statusCode: Status code is not '200'
body: 
{
  "error": "Bad Request: Failed to create Offer, Holding id eiusmod listed as source does not refer to a Holding."
}
statusCode: 400
```

2017-12-13 17:56 UTC, delventhalz approved these changes

2017-12-13 17:57 UTC, merged