CreateOffer TP functionality
hyperledger/sawtooth-marketplace pull request #51
Opened 2017-12-12 21:45 UTC by boydjohnson

This PR is based on #50 and will be rebased once that PR goes into master.

2017-12-12 23:51 UTC, delventhalz requested changes

2017-12-12 23:51 UTC, delventhalz commented on processor/marketplace_processor/offer/offer_creation.py
> +    if create_offer.target and \
As per our discussion on Slack, the TP should also check:
- that the source_quantity is set
- that the target and target_quantity are both set or both unset

2017-12-13 17:03 UTC, delventhalz approved these changes

2017-12-13 19:56 UTC, dplumb94 requested changes
Integration test failure due to `"Failed to create Offer, target and target_quantity must both be set or both unset."`

Some Dredd hooks should be added so that this error doesn't occur

2017-12-13 20:58 UTC, dplumb94 approved these changes

2017-12-13 21:21 UTC, merged