Implement API Fetch Offers
hyperledger/sawtooth-marketplace pull request #54
Opened 2017-12-13 22:53 UTC by dplumb94

2017-12-14 17:14 UTC, delventhalz requested changes
Let's switch the order of the filters. I leave it to your discretion about the test data comment.

2017-12-14 17:14 UTC, delventhalz commented on integration_tests/rest_api/setup_data_hooks.py
> +    OFFER['target'] = seeded_data['holding']['id']
This probably doesn't matter, but do we want to seed two holdings so that source and target don't have to be the same id?

2017-12-14 17:14 UTC, delventhalz commented on rest_api/db/offers_query.py
> +        .filter((blocks_query.latest_block_num() >= r.row['start_block_num'])
The query parameter filter should probably come after the block number filter. My assumption is the block number filter will typically reduce the size of the list more than the query parameters.

2017-12-14 20:24 UTC, delventhalz approved these changes

2017-12-15 15:42 UTC, peterschwarz approved these changes

2017-12-15 15:56 UTC, merged