Add CloseOffer TP functionality
hyperledger/sawtooth-marketplace pull request #63
Opened 2017-12-18 19:19 UTC by boydjohnson

Only the last 2 commits are this PR. The prior 2 will be rebased when #62 goes into master.

2017-12-18 21:24 UTC, dplumb94 requested changes

2017-12-18 21:24 UTC, dplumb94 commented on processor/marketplace_processor/offer/offer_closure.py
> +    if not header.signer_public_key in offer.owners:
Lint error:
`processor/marketplace_processor/offer/offer_closure.py:48:8: E713 test for membership should be 'not in'
    if not header.signer_public_key in offer.owners:
       ^
    Negative comparison should be done using "not in" and "is not".`

2017-12-18 21:26 UTC, dplumb94 commented
Got an error when I ran lint. Otherwise I tested locally and the functionality worked.

2017-12-19 20:08 UTC, dplumb94 approved these changes

2017-12-19 21:20 UTC, delventhalz approved these changes

2017-12-19 22:05 UTC, merged