Implement API Rule value parsing
hyperledger/sawtooth-marketplace pull request #65
Opened 2017-12-19 22:10 UTC by dplumb94

Signed-off-by: Darian Plumb <dplumb@bitwise.io>

2017-12-19 22:21 UTC, boydjohnson commented on rest_api/api/common.py
> +    if not isinstance(value, str) and isinstance(value, (list, tuple)):
Is the `not isinstance(value, str)` necessary here? If the second part is True and value is a list or a tuple, then the first part is automatically also True.

2017-12-20 14:44 UTC, peterschwarz commented on rest_api/api/offers.py
> +    if offer.get('rules') is not None:
Can these be simplified to `dict.get('some_key', None)` or the like?

2017-12-20 18:46 UTC, boydjohnson approved these changes

2017-12-20 22:53 UTC, delventhalz requested changes

2017-12-20 22:53 UTC, delventhalz commented on rest_api/api-spec.yaml
> +        example: ["02178c1bcdb25407394348f1ff5273adae287d8ea328184546837957e71c7de57a"]
This should be:

```
type: array
items:
  type: string
  example: 02178c1bcdb25407394348f1ff5273adae287d8ea328184546837957e71c7de57a
```

2017-12-21 02:28 UTC, delventhalz approved these changes

2017-12-21 15:54 UTC, merged