Implement SawbuckManager fixes raised at demo
hyperledger/sawtooth-marketplace pull request #77
Opened 2017-12-26 20:54 UTC by delventhalz

Fixes Implemented:
- default AcceptOffers to count of 1
- add 1 line of instructions to modals
- truncate labels at 10 char ("New Holding" needs to be shorter)
- validate that you don't go over the Offer owner's quantities
- find a way to make sure data has updated before redirecting on modal close

In addition one bug was noted during the demo, which is in fact already implemented:
- don't allow non-owners to offer non-transferable assets

2017-12-26 20:58 UTC, peterschwarz approved these changes

2017-12-26 22:15 UTC, delventhalz commented
@peterschwarz `@mini.coin`? Is there a standard for making up fake email addresses?

2017-12-26 22:19 UTC, peterschwarz commented
Merely making sure that we're careful about the fake addresses we choose.  You could use `@minicoin.example`, since `.example` will never be a TLD: https://en.wikipedia.org/wiki/.example

2017-12-27 15:55 UTC, dplumb94 commented on sawbuck_app/src/views/accept_offer_modal.js
> +            `Enter how much ${vnode.state.holding.asset} you would like`),
This leads to strange grammar for some offers. Would it be possible to just add the name of each asset over each dropdown, and have the name of the offer in the header?

2017-12-27 16:02 UTC, dplumb94 approved these changes

2017-12-27 21:43 UTC, peterschwarz requested changes

2017-12-27 21:43 UTC, peterschwarz commented on sawbuck_app/app_data.yaml
> +    email: minicoin@minicoin.net
Change this to `minicoin@minicoin.example`

2017-12-28 15:47 UTC, closed without merging